# Generated by Django 4.2.5 on 2023-09-13 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_profile_profileimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profileimg',
        ),
    ]
