# Generated by Django 4.2.5 on 2023-09-13 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='POST',
        ),
    ]
