# Generated by Django 4.2.5 on 2023-09-13 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_posts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
    ]
